### ISSUE TITLE
Add a compilation of the project as a static library

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#549]
We would like to integration continuous deployment for the project and one of the goal as of the project is to create it as a static library for end developer who doesn't have specific libraries/technologies on his/her PC. We use Travis-CI as virtual machine server to continuous integration for MacOS and Linux while AppVeyor is for Windows. We use makefile to project compilation for these platforms.
We need to add an ability to compile static library of the project which would go as a part of deployment for releases.

**Comment by ihhub** [comment]
Hi @yannlabou would you like to have a look at this? It should be interesting to implement. I can help with deployment part as I know how to do it.

**Comment by yannlabou** [comment]
Sounds interesting. Will look deeper at it tonight.

**Comment by ihhub** [comment]
:+1:

**Comment by ihhub** [comment]
@yannlabou you could have a look into [this](https://github.com/ihhub/fheroes2) project which I maintain for check how deployment is done.

**Comment by yannlabou** [comment]
Which part of https://github.com/ihhub/fheroes2 should I particularly check? Further it will be better to create to separate issues for the creation of a static and a dynamic library.

**Comment by ihhub** [comment]
@yannlabou I referred this project as an example for deployment part. In [.travis.yml](https://github.com/ihhub/fheroes2/blob/master/.travis.yml) I've added:
```
# blocklist
branches:
  except:
  - /^fheroes2-windows-.*$/
  - /^fheroes2-linux-.*$/
  - /^fheroes2-osx-.*$/
```
to do not run job on specific tags.
The this part is responsible for deployment preparation and deployment itself:
```
      before_deploy:
        - export TRAVIS_TAG=fheroes2-linux-sdl1-$TRAVIS_BUILD_NUMBER
        - git tag $TRAVIS_TAG
<---- HERE I create a zip archive for deployment --->
        - zip fheroes2_linux_sdl1.zip fheroes2 LICENSE script/linux/install_sdl_1.sh script/linux/install_sdl_2.sh script/demo/demo_linux.sh
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN" <--- HERE I created environment variable inside Travis
        file: "fheroes2_linux_sdl1.zip"
        skip_cleanup: true
        on:
          branch: master <--- HERE we deploy only on master branch
```

**Comment by ihhub** [comment]
For [appveyor.yml](https://github.com/ihhub/fheroes2/blob/master/appveyor.yml):
```
skip_tags: true
```
to do not build on new tags.

Prepare files for deployment (zip archive):
```
after_build:
  - cmd: if "%platform%"=="x86" cd C:\projects\fheroes2\Release
  - cmd: if "%platform%"=="x64" cd C:\projects\fheroes2\x64\Release
  - cmd: 7z a fheroes2.zip fheroes2.exe SDL.dll SDL_mixer.dll
  - cmd: if "%platform%"=="x86" xcopy /Y /s "fheroes2.zip" ".."
  - cmd: if "%platform%"=="x64" xcopy /Y /s "fheroes2.zip" "..\.."
  - cmd: cd C:\projects\fheroes2
  - cmd: 7z a fheroes2.zip script\demo\demo.bat LICENSE
```
Do deployment:
```
deploy:
  release: fheroes2-windows-$(appveyor_build_version)-$(platform)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token: <-- HERE this is encrypted token manually created
    secure: 0KcyoHsROl98QBsNcB+so6hegLvgWZ0R2zYammwgqdDyVXkNDejMjiDpr5sqDnx9
  artifact: /.*\.zip/ <-- HERE deploy all files with zip extension
  draft: false
  prerelease: false
  on:
    branch: master <-- HERE only master branch commits
```
